### ISSUE TITLE
Base58 while loop eats up CPU

### ISSUE THREAD

**Issue by pragmaxim** [ScorexFoundation/scorex-util#28]
It eats up almost 30% of the runtime, taking more time than indexing blocks into database. Completely different implementation `com.google.bitcoin.core.Base58` eats up only 7%.

https://github.com/ScorexFoundation/scorex-util/blob/master/shared/src/main/scala/scorex/util/encode/Base58.scala#L22C1-L26

![Screenshot from 2023-06-16 10-51-14](https://github.com/ScorexFoundation/scorex-util/assets/8983344/a8aaeb7e-f38a-46f8-ad7e-827d20242e36)

Ping https://github.com/ScorexFoundation/scorex-util/issues/27

**Comment by pragmaxim** [comment]
This is how it looks like with `com.google.bitcoin.core.Base58` implementation : 
![Screenshot from 2023-06-20 12-49-39](https://github.com/ScorexFoundation/scorex-util/assets/8983344/35e3d14c-ebd0-407e-bff8-304bedc73ea1)

**Comment by pragmaxim** [comment]
Ok, this implementation of Base58 is extremely slow, `com.google.bitcoin.core.Base58` is ~ 3-4 times faster ... After some further optimizations of blockchain explorer indexing, ~ 45% goes to `com.google.bitcoin.core.Base58`, 15% goes to sigma and 40% to the rest.
![Screenshot from 2023-06-20 15-22-24](https://github.com/ScorexFoundation/scorex-util/assets/8983344/86cd91b3-c2d5-4078-922f-91d9329e1eb2)

**Comment by aslesarenko** [comment]
Thanks for the flame graphs. This is known issue #21, closing this as duplicate.
