### ISSUE TITLE
Extend AnyVal in all implicit classes to avoid allocations

### ISSUE THREAD

**Issue by ergomorphic** [ScorexFoundation/scorex-util#8]
Scala compiler can eliminate allocations of classes inherited from AnyVal.
This applies to implicit classes as well.

Example where this can be applied.
https://github.com/ScorexFoundation/scorex-util/blob/606d4862fd2696b042cf15d28d0cd247af2efc5d/src/main/scala/scorex/util/package.scala#L15

**Comment by aslesarenko** [comment]
This is now done.
